import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'

test('真实会话保存、新建、独立上下文、重命名、切换和删除', async ({ page }) => {
  const failures: string[] = []
  page.on('pageerror', error => failures.push(error.name))
  await page.goto('/chat')
  await page.getByLabel('用户名').fill(process.env.E2E_USERNAME || 'admin')
  await page.getByLabel('密码', { exact: true }).fill(process.env.E2E_PASSWORD || readFileSync('../.local/initial-password.txt', 'utf8').trim())
  await page.getByRole('button', { name: '登录' }).click()
  await page.getByRole('link', { name: 'AI 学习助手', exact: true }).click()
  async function send(query: string) {
    await page.getByLabel('学习问题').fill(query)
    await page.getByRole('button', { name: '发送问题', exact: true }).click()
    await expect(page.getByRole('button', { name: '发送问题', exact: true })).toBeDisabled()
    await expect(page.locator('.chat-message.assistant').last()).toBeVisible()
    await expect(page.locator('.chat-thinking')).toHaveCount(0)
  }
  await page.getByRole('button', { name: '新建聊天', exact: true }).click()
  await expect(page.getByRole('heading', { name: '新建学习对话' })).toBeVisible()
  await expect(page).toHaveURL(/conversation=[a-f0-9-]+/)
  const first = new URL(page.url()).searchParams.get('conversation')!
  await send('会话 A 的学习暗号是循序积累')
  await expect(page.locator('.conversation-header h2')).toHaveText('会话 A 的学习暗号是循序积累')
  await page.reload()
  await expect(page.locator('.chat-message.user')).toContainText('会话 A 的学习暗号是循序积累')
  await send('查询当前聊天上下文 A')
  await expect(page.locator('.chat-message.assistant').last()).toContainText('会话 A 的学习暗号是循序积累')
  await page.getByRole('button', { name: '新建聊天', exact: true }).click()
  await expect(page).not.toHaveURL(new RegExp(first))
  const second = new URL(page.url()).searchParams.get('conversation')!
  expect(second).not.toBe(first)
  await expect(page.locator('.chat-message')).toHaveCount(0)
  await send('查询当前聊天上下文 B')
  await expect(page.locator('.chat-message.assistant').last()).toContainText('新聊天没有历史上下文')
  await expect(page.locator('.chat-message.assistant').last()).not.toContainText('循序积累')
  await page.getByRole('button', { name: '重命名聊天：查询当前聊天上下文 B', exact: true }).click()
  await page.getByLabel('聊天名称', { exact: true }).fill('独立的资料分析对话')
  await page.getByRole('button', { name: '保存名称', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page.locator('.conversation-header h2')).toHaveText('独立的资料分析对话')
  await page.getByRole('button', { name: '打开聊天：会话 A 的学习暗号是循序积累', exact: true }).click()
  await expect(page.locator('.chat-message')).toHaveCount(4)
  await page.getByLabel('学习问题').fill('慢速验收：只属于会话 A 的回复')
  await page.getByRole('button', { name: '发送问题', exact: true }).click()
  await expect(page.locator('.chat-thinking')).toBeVisible()
  await page.getByRole('button', { name: '打开聊天：独立的资料分析对话', exact: true }).click()
  await expect(page.locator('.chat-message')).toHaveCount(2)
  await expect(page.locator('.chat-messages')).not.toContainText('只属于会话 A 的回复')
  await page.getByRole('button', { name: '打开聊天：会话 A 的学习暗号是循序积累', exact: true }).click()
  await expect(page.locator('.chat-message.assistant').last()).toContainText('只属于会话 A 的回复', { timeout: 15000 })
  const fixture = process.env.E2E_AI_URL!
  const captured = await (await page.request.get(fixture + '/_test/chat-calls')).json()
  expect(captured.find((item: { query: string }) => item.query === '查询当前聊天上下文 B').history).toEqual([])
  expect(JSON.stringify(captured.find((item: { query: string }) => item.query === '查询当前聊天上下文 A').history)).toContain('循序积累')
  expect(JSON.stringify(captured.find((item: { query: string }) => item.query === '查询当前聊天上下文 A').history)).not.toContain('上下文 B')

  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '切换深色', exact: true }).click()
  await page.getByRole('button', { name: '聊天历史', exact: true }).click()
  await expect(page.getByRole('button', { name: '新建聊天', exact: true })).toBeVisible()
  await page.getByLabel('搜索聊天历史').fill('独立的资料')
  await expect(page.locator('.conversation-row')).toHaveCount(1)
  await page.getByRole('button', { name: '打开聊天：独立的资料分析对话', exact: true }).click()
  await expect(page.locator('.chat-message')).toHaveCount(2)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: '聊天历史', exact: true }).click()
  await page.getByLabel('搜索聊天历史').fill('')
  await page.getByRole('button', { name: '删除聊天：独立的资料分析对话', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('无法恢复')
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.getByRole('button', { name: '打开聊天：独立的资料分析对话', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '删除聊天：独立的资料分析对话', exact: true }).click()
  await page.getByRole('button', { name: '确认删除', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  expect(new URL(page.url()).searchParams.get('conversation')).toBe(first)
  await expect(page.locator('.chat-message.assistant').last()).toContainText('只属于会话 A 的回复')
  await page.reload()
  await page.getByRole('button', { name: '聊天历史', exact: true }).click()
  await expect(page.getByRole('button', { name: '打开聊天：独立的资料分析对话', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '删除聊天：会话 A 的学习暗号是循序积累', exact: true }).click()
  await page.getByRole('button', { name: '确认删除', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page.getByRole('heading', { name: '新建学习对话' })).toBeVisible()
  expect(failures).toEqual([])
})
