import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { execFileSync, spawnSync } from 'node:child_process'

test('真实浏览器：登录、录题、编辑、刷新会话和手机布局', async ({ page }) => {
  const password = process.env.E2E_PASSWORD || readFileSync('../.local/initial-password.txt', 'utf8').trim()
  const username = process.env.E2E_USERNAME || 'admin'
  const failures: string[] = []
  page.on('pageerror', error => failures.push(error.name))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '登录知序' })).toBeVisible()
  await page.getByLabel('用户名').fill(username)
  await page.getByLabel('密码', { exact: true }).fill(password)
  await page.getByRole('button', { name: '登录' }).click()
  await expect(page.getByRole('heading', { name: '今日学习', exact: true })).toBeVisible()
  await page.getByRole('link', { name: '录入错题' }).click()
  await page.getByLabel('题目', { exact: true }).fill('浏览器集成测试：100 增长到 120 的增长率？')
  await page.getByLabel('选项 A', { exact: true }).fill('10%')
  await page.getByLabel('选项 B', { exact: true }).fill('20%')
  await page.getByLabel('正确答案', { exact: true }).selectOption('B')
  await page.getByLabel('我的答案', { exact: true }).selectOption('A')
  await page.getByLabel('确认错因').selectOption('计算错误')
  await page.getByRole('button', { name: '保存题目', exact: true }).click()
  await expect(page.getByRole('heading', { name: '错题复盘' })).toBeVisible()
  await expect(page.getByText('浏览器集成测试：100 增长到 120 的增长率？', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: '编辑题目' }).click()
  await page.getByLabel('参考解析').fill('测试参考解析：(120-100)/100 = 20%。')
  await page.getByRole('button', { name: '保存题目', exact: true }).click()
  await expect(page.getByText('测试参考解析：(120-100)/100 = 20%。', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: '错题复盘' })).toBeVisible()
  const questionId = page.url().split('/').pop()!
  const schema = process.env.E2E_SCHEMA || ''
  expect(schema).toMatch(/^e2e_[0-9]+_[0-9]+$/)
  expect(questionId).toMatch(/^[a-f0-9-]{36}$/)
  const dockerArgs = ['compose','exec','-T','postgres','sh','-c','psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -v ON_ERROR_STOP=1 -c "$1"','sh',`UPDATE ${schema}.review_plans SET next_review_at=now()-interval '1 day' WHERE question_id='${questionId}'`]
  if (spawnSync('docker', ['info'], { stdio: 'ignore' }).status === 0) execFileSync('docker', dockerArgs, { cwd: '..', stdio: 'ignore' })
  else execFileSync('sudo', ['-n','docker',...dockerArgs], { cwd: '..', stdio: 'ignore' })
  await page.getByRole('link', { name: '每日复习', exact: true }).click()
  await page.getByRole('radio', { name: 'B 20%' }).check()
  await page.getByRole('button', { name: '提交答案' }).click()
  await expect(page.getByRole('heading', { name: '回答正确' })).toBeVisible()
  await page.getByRole('button', { name: '完成复习' }).click()
  await expect(page.getByRole('heading', { name: '本次复习已完成' })).toBeVisible()
  await page.getByRole('link', { name: '成语与词语', exact: true }).click()
  await page.getByRole('button', { name: '添加词语' }).click()
  await page.getByLabel('词语', { exact: true }).fill('循序渐进')
  await page.getByLabel('释义', { exact: true }).fill('测试：按次序逐步前进。')
  await page.getByRole('button', { name: '保存词语' }).click()
  await expect(page.getByRole('heading', { name: '循序渐进' }).first()).toBeVisible()
  await page.getByRole('button', { name: '收藏' }).click()
  await expect(page.getByRole('button', { name: '已收藏' })).toBeVisible()
  await page.getByRole('link', { name: '申论素材', exact: true }).click()
  await page.getByRole('button', { name: '添加素材', exact: true }).click()
  await page.getByLabel('标题', { exact: true }).fill('浏览器测试素材')
  await page.getByLabel('素材内容', { exact: true }).fill('仅在隔离 schema 中验证素材录入。')
  await page.getByRole('button', { name: '保存素材', exact: true }).click()
  await expect(page.getByRole('heading', { name: '浏览器测试素材' })).toBeVisible()
  await page.getByRole('link', { name: '每日时政', exact: true }).click()
  await page.getByRole('button', { name: '手动收录' }).click()
  await page.getByLabel('标题', { exact: true }).fill('浏览器测试时政原文')
  await page.getByLabel('原文内容', { exact: true }).fill('仅用于验证来源原文保存的测试材料。')
  await page.getByLabel('来源名称', { exact: true }).fill('隔离测试文档')
  await page.getByRole('button', { name: '保存原文' }).click()
  await expect(page.getByRole('heading', { name: '1. 浏览器测试时政原文' })).toBeVisible()
  await expect(page.getByText('来源待核实', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: '学习统计', exact: true }).click()
  await expect(page.getByRole('table')).toBeVisible()
  await expect(page.getByRole('img', { name: '每日练习、错题和复习完成数量趋势' })).toBeVisible()
  await page.getByRole('link', { name: '学习周报', exact: true }).click()
  await page.getByRole('button', { name: '生成 / 更新本周周报' }).click()
  await expect(page.getByRole('heading', { name: '复习完成情况' })).toBeVisible()
  await page.getByRole('link', { name: 'AI 学习助手', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'AI 学习助手', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'AI 申论助手', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'AI 申论助手', exact: true })).toBeVisible()
  expect(await page.evaluate(() => Object.keys(localStorage).some(key => /token|password/i.test(key)))).toBe(false)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('link', { name: '今日学习', exact: true }).click()
  await expect(page.getByRole('heading', { name: '今日学习', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: '切换深色' }).click()
  await expect(page.locator('html')).toHaveClass('dark')
  await page.screenshot({ path: '../.local/mobile-dashboard.png', fullPage: true })
  await page.getByRole('button', { name: '退出登录' }).click()
  await expect(page.getByRole('heading', { name: '登录知序' })).toBeVisible()
  expect(failures).toEqual([])
})
