import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'

test('自定义模型：真实保存、密钥不回显、失败保留、编辑、实际调用与移除', async ({ page }) => {
  const failures: string[] = []
  page.on('pageerror', error => failures.push(error.name))
  page.on('console', message => { if (message.type() === 'error' && !message.text().includes('503') && !message.text().includes('401')) failures.push(message.text()) })
  await page.goto('/')
  await page.getByLabel('用户名').fill(process.env.E2E_USERNAME || 'admin')
  await page.getByLabel('密码', { exact: true }).fill(process.env.E2E_PASSWORD || readFileSync('../.local/initial-password.txt', 'utf8').trim())
  await page.getByRole('button', { name: '登录', exact: true }).click()
  const selector = page.getByLabel('AI 模型', { exact: true })
  await expect(selector).toBeEnabled()
  await page.setViewportSize({ width: 1448, height: 1086 })
  await page.getByRole('button', { name: '管理模型', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '模型接入', exact: true })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: '添加接入', exact: true }).click()
  await expect(dialog.getByLabel('提供商', { exact: true })).toBeFocused()
  await dialog.getByLabel('提供商', { exact: true }).fill('我的自定义模型')
  await dialog.getByLabel('Base URL', { exact: true }).fill('https://models.example/v1/')
  await dialog.getByLabel('API Key', { exact: true }).fill('e2e-custom-model-key')
  await dialog.getByLabel('模型名称', { exact: true }).fill('custom-chat')
  await expect(dialog.getByLabel('API Key', { exact: true })).toHaveAttribute('type', 'password')
  await dialog.getByRole('button', { name: '显示 API Key', exact: true }).click()
  await expect(dialog.getByLabel('API Key', { exact: true })).toHaveAttribute('type', 'text')
  await dialog.getByRole('button', { name: '隐藏 API Key', exact: true }).click()
  if (process.env.E2E_SCREENSHOT_DIR) await page.screenshot({ path: process.env.E2E_SCREENSHOT_DIR + '/zhixu-model-form-desktop.png' })
  const responsePromise = page.waitForResponse(response => response.url().endsWith('/api/ai-models/connections') && response.request().method() === 'POST')
  await dialog.getByRole('button', { name: '验证并使用', exact: true }).click()
  const saved = await (await responsePromise).json()
  expect(JSON.stringify(saved)).not.toContain('e2e-custom-model-key')
  expect(saved.connections[0].hasApiKey).toBe(true)
  const id = saved.activeConnectionId
  await expect(dialog.getByRole('status')).toHaveText('连接测试通过，已保存并使用')
  await expect(dialog.getByText('正在使用', { exact: true })).toHaveCount(1)
  if (process.env.E2E_SCREENSHOT_DIR) await page.screenshot({ path: process.env.E2E_SCREENSHOT_DIR + '/zhixu-model-manager-desktop.png' })
  await dialog.getByRole('button', { name: '添加接入', exact: true }).click()
  await dialog.getByLabel('提供商', { exact: true }).fill('连接失败的提供商')
  await dialog.getByLabel('Base URL', { exact: true }).fill('https://models.example/v1')
  await dialog.getByLabel('API Key', { exact: true }).fill('invalid-e2e-key')
  await dialog.getByLabel('模型名称', { exact: true }).fill('custom-bad')
  await dialog.getByRole('button', { name: '验证并使用', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('连接失败')
  await dialog.getByRole('button', { name: '返回', exact: true }).click()
  await expect(dialog.locator('.model-connections li')).toHaveCount(1)
  await dialog.getByRole('button', { name: '编辑 我的自定义模型', exact: true }).click()
  await expect(dialog.getByLabel('API Key', { exact: true })).toHaveValue('')
  await expect(dialog.getByText('已保存，留空沿用原密钥', { exact: true })).toBeVisible()
  await dialog.getByLabel('模型名称', { exact: true }).fill('custom-chat-edited')
  await dialog.getByRole('checkbox', { name: /^启用 JSON 模式/ }).uncheck()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  if (process.env.E2E_SCREENSHOT_DIR) await page.screenshot({ path: process.env.E2E_SCREENSHOT_DIR + '/zhixu-model-form-mobile.png' })
  await dialog.getByRole('button', { name: '验证并使用', exact: true }).click()
  await expect(dialog.getByRole('status')).toHaveText('连接测试通过，已保存并使用')
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('button', { name: '管理模型', exact: true })).toBeFocused()
  await expect(selector).toHaveValue('@' + id)
  expect(await page.evaluate(() => Object.keys(localStorage).some(key => /token|key|password|model/i.test(key)))).toBe(false)
  await page.reload()
  await expect(selector).toHaveValue('@' + id)
  await page.getByRole('link', { name: 'AI 学习助手', exact: true }).click()
  await page.getByLabel('学习问题', { exact: true }).fill('自定义模型接入验收')
  await page.getByRole('button', { name: '发送问题', exact: true }).click()
  await expect(page.getByText('已记录这次提问', { exact: false }).last()).toBeVisible()
  const fixture = process.env.E2E_AI_URL
  expect(fixture).toMatch(/^http:\/\/127\.0\.0\.1:\d+$/)
  const calls = await (await page.request.get(fixture + '/_test/chat-calls')).json()
  const called = calls.find((item: { query: string }) => item.query === '自定义模型接入验收')
  expect(called.model).toBe('custom-chat-edited')
  expect(called.baseUrl).toBe('https://models.example/v1')
  expect(called.customCredentialPresent).toBe(true)
  await page.getByRole('button', { name: '管理模型', exact: true }).click()
  await dialog.getByRole('button', { name: '使用默认', exact: true }).click()
  await expect(dialog.getByRole('status')).toHaveText('连接测试通过，已切换')
  await dialog.getByRole('button', { name: '移除 我的自定义模型', exact: true }).click()
  await dialog.getByRole('button', { name: '保留', exact: true }).click()
  await expect(dialog.getByRole('button', { name: '确认移除', exact: true })).not.toBeVisible()
  await dialog.getByRole('button', { name: '移除 我的自定义模型', exact: true }).click()
  await dialog.getByRole('button', { name: '确认移除', exact: true }).click()
  await expect(dialog.getByRole('status')).toHaveText('模型接入已移除')
  await expect(dialog.locator('.model-connections li')).toHaveCount(0)
  await dialog.getByRole('button', { name: '关闭模型管理', exact: true }).click()
  await page.setViewportSize({ width: 320, height: 740 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(failures).toEqual([])
})
