import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'

test('时政原文直达、持久化标签筛选及各页面可视化', async ({ page }) => {
  const failures: string[] = []
  page.on('pageerror', error => failures.push(error.name))
  await page.goto('/news')
  await page.getByLabel('用户名').fill(process.env.E2E_USERNAME || 'admin')
  await page.getByLabel('密码', { exact: true }).fill(process.env.E2E_PASSWORD || readFileSync('../.local/initial-password.txt', 'utf8').trim())
  await page.getByRole('button', { name: '登录' }).click()
  await page.getByRole('link', { name: '每日时政', exact: true }).click()
  async function create(title: string, source: string, url: string, tag: string) {
    await page.getByRole('button', { name: '手动收录', exact: true }).click()
    await page.getByLabel('标题', { exact: true }).fill(title)
    await page.getByLabel('原文内容', { exact: true }).fill('只在随机隔离 schema 中保存的原文，用于验证真实 API、分类与来源。')
    await page.getByLabel('来源名称', { exact: true }).fill(source)
    await page.getByLabel('原始来源链接', { exact: true }).fill(url)
    await page.getByRole('checkbox', { name: tag, exact: true }).check()
    await page.getByRole('button', { name: '保存原文', exact: true }).click()
    await expect(page.getByRole('heading', { name: new RegExp(title) })).toBeVisible()
  }
  await create('科技创新标签浏览器验收', '隔离来源甲', 'https://source.example/tech-visual-test', '科技')
  await create('经济政策标签浏览器验收', '隔离来源乙', 'https://source.example/economy-visual-test', '经济')
  const original = page.getByRole('link', { name: '查看原文：科技创新标签浏览器验收', exact: true })
  await expect(original).toHaveAttribute('href', 'https://source.example/tech-visual-test')
  await expect(original).toHaveAttribute('target', '_blank')
  await expect(original).toHaveAttribute('rel', 'noopener noreferrer')
  await page.getByRole('button', { name: '查看主题与来源分布', exact: true }).click()
  await expect(page.getByRole('img', { name: '当日时政各主题标签的文章数量' })).toBeVisible()
  await expect(page.getByRole('img', { name: '当日收录时政的新闻来源分布' })).toBeVisible()
  await page.locator('.tag-filters').getByRole('button', { name: /^科技/ }).click()
  await expect(page.getByRole('heading', { name: /科技创新标签浏览器验收/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: /经济政策标签浏览器验收/ })).toHaveCount(0)
  await page.getByLabel('新闻来源筛选').selectOption('隔离来源乙')
  await expect(page.getByRole('heading', { name: '没有符合筛选条件的时政' })).toBeVisible()
  await page.getByRole('button', { name: '清除筛选', exact: true }).click()
  const article = page.locator('article').filter({ has: page.getByRole('heading', { name: /科技创新标签浏览器验收/ }) })
  await article.getByRole('button', { name: '编辑标签', exact: true }).click()
  await page.getByRole('checkbox', { name: '科技', exact: true }).uncheck()
  await page.getByRole('checkbox', { name: '民生', exact: true }).check()
  await page.getByRole('button', { name: '保存标签', exact: true }).click()
  await expect(article.getByRole('button', { name: '民生', exact: true })).toBeVisible()
  await page.reload()
  await expect(article.getByRole('button', { name: '民生', exact: true })).toBeVisible()
  await expect(article.getByText('手动分类', { exact: true })).toBeVisible()
  await page.getByLabel('搜索时政').fill('科技创新标签浏览器验收')
  await page.getByRole('button', { name: '刷新日报', exact: true }).click()
  await expect(page.locator('article')).toHaveCount(1)
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(original).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: '切换深色' }).click()
  await expect(page.locator('html')).toHaveClass('dark')
  await page.screenshot({ path: '../.local/news-visuals-mobile-test.png', fullPage: true })
  await page.getByRole('link', { name: '今日学习', exact: true }).click()
  await expect(page.getByRole('progressbar', { name: '今日任务完成情况', exact: true })).toBeVisible()
  await expect(page.locator('.study-metrics').getByText('今日练习', { exact: true })).toBeVisible()
  await expect(page.getByRole('img', { name: '最近七天练习、错题和复习数量', exact: true }).or(page.getByText('最近 7 天暂无学习记录。记录练习或完成复习后，可在这里查看趋势。', { exact: true }))).toBeVisible()
  await page.getByRole('link', { name: '知识体系', exact: true }).click()
  await expect(page.getByRole('heading', { name: '优先巩固的知识点', exact: true })).toBeVisible()
  await page.getByRole('link', { name: '处理进度', exact: true }).click()
  await expect(page.getByRole('img', { name: '最近一百项后台任务的等待、处理、完成和失败分布', exact: true })).toBeVisible()
  await expect(page.getByRole('progressbar', { name: '最近任务完成比例', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(failures).toEqual([])
})
