<script setup lang="ts">
import PageHeader from '../components/PageHeader.vue'
import { ref } from 'vue'
import Citations, { type Reference } from '../components/Citations.vue'
import MarkdownContent from '../components/MarkdownContent.vue'
import { api, errorText } from '../lib/api'
interface Result { topic: string; outline: { background: string; problems: string[]; causes: string[]; solutions: string[]; cases: string[]; quotes: string[] }; citations: Reference[]; retrievalStatus: string }
const topic = ref(''), error = ref(''), busy = ref(false), result = ref<Result | null>(null)
async function generate() { busy.value = true; error.value = ''; result.value = null; try { result.value = (await api.post<Result>('/essay-assistant', { topic: topic.value }, { timeout: 180000 })).data } catch (e) { error.value = errorText(e) } finally { busy.value = false } }
async function save() { if (!result.value) return; try { const outline = result.value.outline; const content = ['背景\n'+outline.background,...[['问题',outline.problems],['原因',outline.causes],['对策',outline.solutions],['案例',outline.cases],['金句',outline.quotes]].map(([title,items])=>title+'\n'+(items as string[]).join('\n'))].join('\n\n'); await api.post('/essay-materials', { title: result.value.topic + ' · 学习提纲', content, category: '社会治理', kind: '观点', tags: [result.value.topic], source: 'AI 整理的个人学习笔记', sourceUnverified: true }); error.value = ''; saved.value = true } catch (e) { error.value = errorText(e) } }
const saved = ref(false)
</script>
<template><PageHeader title="AI 申论助手"><RouterLink class="text-button" to="/materials">查看素材库</RouterLink></PageHeader><form class="panel essay-entry" @submit.prevent="saved = false; generate()"><label for="essay-topic">训练主题</label><div class="toolbar"><input id="essay-topic" v-model="topic" required maxlength="300" placeholder="例如：基层治理、乡村振兴、数字政府"><button class="button" :disabled="busy">{{ busy ? '正在整理…' : '整理学习提纲' }}</button></div><p class="muted">提纲包含背景、问题、对策和案例。</p></form><p v-if="busy" class="loading-state" role="status">正在读取资料并整理学习提纲…</p><p v-if="error" class="error section-gap" role="alert">{{ error }}</p><section v-if="result" class="panel section-gap essay-result"><h2>{{ result.topic }} · 学习提纲</h2><p v-if="result.retrievalStatus !== 'VECTOR_AND_DATABASE'" class="muted">本次基于实际数据库资料整理。</p><h3>背景</h3><MarkdownContent :content="result.outline.background || '资料不足，尚未形成背景。'" /><div v-for="[title,items] in [['问题',result.outline.problems],['原因',result.outline.causes],['对策',result.outline.solutions],['案例',result.outline.cases],['金句',result.outline.quotes]]" :key="String(title)"><h3>{{ title }}</h3><ul v-if="(items as string[]).length" class="reading"><li v-for="item in items" :key="String(item)"><MarkdownContent :content="String(item)" /></li></ul><p v-else class="muted">已有资料中暂无可整理的内容。</p></div><Citations :references="result.citations"></Citations><div class="actions section-gap"><button class="button secondary" :disabled="saved" @click="save">{{ saved ? '已保存到素材库' : '保存为学习笔记' }}</button></div></section></template>
