<script setup lang="ts">
import PageHeader from '../components/PageHeader.vue'
import AppModal from '../components/AppModal.vue'
import EmptyState from '../components/EmptyState.vue'
import { computed, onMounted, ref } from 'vue'
import AppIcon from '../components/AppIcon.vue'
import MetricCard from '../components/MetricCard.vue'
import StudyChart from '../components/StudyChart.vue'
import { api, errorText, type KnowledgePoint } from '../lib/api'
const items = ref<KnowledgePoint[]>([]), error = ref(''), open = ref(false), editing = ref(''), busy = ref(false), loading = ref(true)
const measured = computed(() => items.value.filter(point => point.practiceCount > 0))
const mastered = computed(() => measured.value.filter(point => point.mastery >= 80).length)
const weak = computed(() => measured.value.filter(point => point.mastery < 60).length)
const masteryChart = computed(() => { const points = [...measured.value].sort((a, b) => a.mastery - b.mastery).slice(0, 10); return { tooltip: { trigger: 'axis', valueFormatter: (value: unknown) => value + '%' }, grid: { left: 110, right: 45, top: 12, bottom: 30 }, xAxis: { type: 'value', max: 100, axisLabel: { formatter: '{value}%' } }, yAxis: { type: 'category', inverse: true, data: points.map(point => point.name) }, series: [{ type: 'bar', barMaxWidth: 18, label: { show: true, position: 'right', formatter: '{c}%' }, data: points.map(point => point.mastery) }] } })
const form = ref({ name: '', parentId: null as string | null, description: '' })
async function load() { loading.value = true; try { items.value = (await api.get<KnowledgePoint[]>('/knowledge-points')).data; error.value = '' } catch (e) { error.value = errorText(e) } finally { loading.value = false } }
function edit(point?: KnowledgePoint) { editing.value = point?.id || ''; form.value = { name: point?.name || '', parentId: point?.parentId || null, description: point?.description || '' }; open.value = true }
async function save() { busy.value = true; try { if (editing.value) await api.put(`/knowledge-points/${editing.value}`, form.value); else await api.post('/knowledge-points', form.value); open.value = false; await load() } catch (e) { error.value = errorText(e) } finally { busy.value = false } }
async function remove(id: string) { if (!confirm('删除此知识点？仍有关联题目或子节点时会保留。')) return; try { await api.delete(`/knowledge-points/${id}`); await load() } catch (e) { error.value = errorText(e) } }
function parentName(id: string | null) { return items.value.find(x => x.id === id)?.name || '一级知识点' }
onMounted(load)
</script>
<template><PageHeader title="知识体系"><button class="button" @click="edit()"><AppIcon name="plus" :size="17" />添加知识点</button></PageHeader><p v-if="error" class="error" role="alert">{{ error }}</p><div class="stat-grid"><MetricCard label="知识点" :value="items.length" unit="个" icon="network" /><MetricCard label="有练习记录" :value="measured.length" unit="个" icon="pen" /><MetricCard label="掌握度 ≥ 80%" :value="mastered" unit="个" icon="check" /><MetricCard label="掌握度 ＜ 60%" :value="weak" unit="个" icon="target" tone="amber" /></div><section class="panel section-gap"><h2><AppIcon name="chart" />优先巩固的知识点</h2><StudyChart v-if="measured.length" :option="masteryChart" label="有练习记录的知识点掌握度，展示最低的十项" /><p v-else class="empty">关联题目并完成练习或复习后，展示真实掌握度。</p></section><p v-if="loading" class="loading-state" role="status">正在读取知识点…</p><EmptyState v-else-if="!items.length && !error" class="section-gap" title="暂无知识点" description="添加知识点或通过错题分析自动提取。" icon="network"><button class="button" @click="edit()">添加知识点</button></EmptyState><section v-if="items.length" class="panel section-gap"><div v-for="point in items" :key="point.id" class="knowledge-row"><div><small>{{ parentName(point.parentId) }}</small><h3>{{ point.name }}</h3><p class="muted">{{ point.description || '暂无补充说明' }} · {{ point.questionCount }} 道关联题</p></div><div class="knowledge-score"><span>{{ point.practiceCount ? point.mastery + '%' : '待练习' }}</span><progress v-if="point.practiceCount" :value="point.mastery" max="100" :aria-label="point.name + '掌握度'"></progress></div><button class="text-button" @click="edit(point)">编辑</button><button class="text-button danger" @click="remove(point.id)">删除</button></div></section><AppModal v-model:open="open" :title="editing ? '编辑知识点' : '添加知识点'" :busy="busy"><form @submit.prevent="save"><h2>{{ editing ? '编辑知识点' : '添加知识点' }}</h2><label>名称<input v-model="form.name" required maxlength="200"></label><label>父知识点<select v-model="form.parentId"><option :value="null">一级知识点</option><option v-for="point in items.filter(x => x.id !== editing)" :key="point.id" :value="point.id">{{ point.name }}</option></select></label><label>补充说明<textarea v-model="form.description" rows="4" maxlength="20000"></textarea></label><p v-if="error" class="error">{{ error }}</p><div class="actions"><button type="button" class="button secondary" :disabled="busy" @click="open = false">取消</button><button class="button" :disabled="busy">保存知识点</button></div></form></AppModal></template>
