<script setup lang="ts">
import AppIcon from '../components/AppIcon.vue'
import PageHeader from '../components/PageHeader.vue'
import EmptyState from '../components/EmptyState.vue'
import { onMounted, ref } from 'vue'
import { api, errorText, questionTypes, taskLabel, formatTime, type Question } from '../lib/api'
const items = ref<Question[]>([]), total = ref(0), page = ref(1), q = ref(''), type = ref(''), error = ref(''), loading = ref(false)
async function load(reset = false) { if (reset) page.value = 1; loading.value = true; try { const { data } = await api.get<{ items: Question[]; total: number }>('/questions', { params: { q: q.value, type: type.value, page: page.value, pageSize: 20 } }); items.value = data.items; total.value = data.total; error.value = '' } catch (e) { error.value = errorText(e) } finally { loading.value = false } }
onMounted(() => load())
</script>
<template><PageHeader title="错题笔记"><template #description><p class="muted">共 {{ total }} 道题目</p></template><RouterLink class="button" to="/questions/new"><AppIcon name="plus" :size="17" />录入错题</RouterLink></PageHeader><form class="toolbar" @submit.prevent="load(true)"><input v-model="q" placeholder="搜索题目内容" aria-label="搜索题目"><select v-model="type" @change="load(true)" aria-label="题型"><option value="">全部题型</option><option v-for="name in questionTypes" :key="name">{{ name }}</option></select><button class="button secondary">搜索</button></form><p v-if="error" class="error" role="alert">{{ error }}</p><p v-if="loading" class="loading-state" role="status">正在读取题目…</p><EmptyState v-else-if="!items.length && !error" :title="q || type ? '没有找到相关题目' : '还没有错题'" :description="q || type ? '换一个关键词或题型，重新查找你的错题笔记。' : '录入题目后，可查看解析并安排复习。'" icon="book"><button v-if="q || type" class="button secondary" @click="q = ''; type = ''; load(true)">清除筛选</button><RouterLink v-else class="button" to="/questions/new">录入错题</RouterLink></EmptyState><RouterLink v-for="(question, index) in items" :key="question.id" :to="`/questions/${question.id}`" class="question-card"><span class="question-index" aria-hidden="true">{{ String((page - 1) * 20 + index + 1).padStart(2, '0') }}</span><div class="question-card-content"><div class="actions"><span class="tag">{{ question.questionType }}</span><span class="tag neutral">{{ question.difficulty }}</span><span class="badge right">{{ taskLabel(question.aiStatus) }}</span></div><p class="reading clamp">{{ question.content }}</p><div v-if="Object.keys(question.options).length" class="question-preview-options"><span v-for="(option, key) in question.options" :key="key">{{ key }}. {{ option }}</span></div><div class="question-meta"><span>{{ question.knowledgePoints.join(' · ') || '等待知识点分类' }}</span><span>{{ formatTime(question.createdAt) }}</span></div></div><AppIcon class="question-open" name="arrow-right" :size="17" /></RouterLink><div v-if="total > 20" class="pagination"><button class="button secondary" :disabled="page === 1" @click="page--; load()">上一页</button><span>{{ page }} / {{ Math.ceil(total / 20) }}</span><button class="button secondary" :disabled="page * 20 >= total" @click="page++; load()">下一页</button></div></template>
