<script setup lang="ts">
import PageHeader from '../components/PageHeader.vue'
import { onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api, errorText, questionTypes, reasons, type Question } from '../lib/api'
const route = useRoute(), router = useRouter(), error = ref(''), busy = ref(false), loading = ref(Boolean(route.params.id)), points = ref('')
const form = reactive({ content: '', correctAnswer: 'A', userAnswer: '', explanation: '', questionType: '常识判断', difficulty: '中等', mistakeReason: '未确认', source: '', year: null as number | null, region: '', mistake: true, options: { A: '', B: '', C: '', D: '' } as Record<string,string>, clientRequestId: crypto.randomUUID() })
onMounted(async () => { if (route.params.id) try { const { data } = await api.get<Question>(`/questions/${route.params.id}`); Object.assign(form, data); points.value = data.knowledgePoints.join('，') } catch (e) { error.value = errorText(e) } finally { loading.value = false } })
async function save() { busy.value = true; error.value = ''; try { const body = { ...form, year: form.year || null, options: form.questionType === '申论' ? {} : Object.fromEntries(Object.entries(form.options).filter(([,value]) => value.trim())), knowledgePoints: points.value.split(/[，,、\n]/).map(x => x.trim()).filter(Boolean) }; const response = route.params.id ? await api.put(`/questions/${route.params.id}`, body) : await api.post('/questions', body); await router.push(`/questions/${response.data.id}`) } catch (e) { error.value = errorText(e) } finally { busy.value = false } }
</script>
<template><PageHeader visible-title :title="route.params.id ? '编辑题目' : '录入一道错题'"><template #description><p class="muted">先保存题目，随后自动进行分析和知识点整理。</p></template><RouterLink class="text-button" to="/questions">返回题目列表</RouterLink></PageHeader><p v-if="loading" class="panel empty">正在读取题目…</p><form v-else class="panel editor-form" @submit.prevent="save"><h2 class="form-section-title">题目内容</h2><div class="form-grid"><label>题型<select v-model="form.questionType"><option v-for="type in questionTypes" :key="type">{{ type }}</option></select></label><label>难度<select v-model="form.difficulty"><option>简单</option><option>中等</option><option>困难</option></select></label></div><label>题目<textarea v-model="form.content" required rows="6" maxlength="20000" placeholder="输入题干、材料或申论练习要求"></textarea></label><div v-if="form.questionType !== '申论'" class="form-grid"><label v-for="key in Object.keys(form.options)" :key="key">选项 {{ key }}<textarea v-model="form.options[key]" rows="2" maxlength="5000" :required="key === 'A' || key === 'B'"></textarea></label></div><h2 class="form-section-title">作答与解析</h2><div class="form-grid"><label>正确答案<textarea v-if="form.questionType === '申论'" v-model="form.correctAnswer" aria-label="正确答案" required maxlength="5000"></textarea><select v-else v-model="form.correctAnswer" aria-label="正确答案"><option v-for="key in Object.keys(form.options)" :key="key">{{ key }}</option></select></label><label>我的答案<textarea v-if="form.questionType === '申论'" v-model="form.userAnswer" aria-label="我的答案" maxlength="5000"></textarea><select v-else v-model="form.userAnswer" aria-label="我的答案"><option value="">未作答</option><option v-for="key in Object.keys(form.options)" :key="key">{{ key }}</option></select></label></div><label>参考解析<textarea v-model="form.explanation" rows="4" maxlength="20000" aria-describedby="explanation-format"></textarea></label><p id="explanation-format" class="muted">支持 Markdown 排版和 LaTeX 数学公式，保存后可在错题详情与每日复习中查看渲染效果。</p><h2 class="form-section-title">知识点与来源</h2><div class="form-grid"><label>知识点（用逗号分隔）<input v-model="points" placeholder="如：增长率，基期量"></label><label>确认错因<select v-model="form.mistakeReason"><option>未确认</option><option v-for="reason in reasons" :key="reason">{{ reason }}</option></select></label><label>题目来源<input v-model="form.source" maxlength="300"></label><label>考试地区<input v-model="form.region" maxlength="100"></label><label>年份<input v-model.number="form.year" type="number" min="1980" max="2100"></label><label class="checkbox-label"><input v-model="form.mistake" type="checkbox">加入错题与复习计划</label></div><p v-if="error" class="error" role="alert">{{ error }}</p><div class="actions"><button class="button" :disabled="busy">{{ busy ? '正在保存…' : '保存题目' }}</button><RouterLink class="button secondary" to="/questions">取消</RouterLink></div></form></template>
