<script setup lang="ts">
import PageHeader from '../components/PageHeader.vue'
import MarkdownContent from '../components/MarkdownContent.vue'
import { computed, onMounted, ref } from 'vue'
import { api, errorText, formatTime, type Question } from '../lib/api'
import AppIcon from '../components/AppIcon.vue'
import ProgressMeter from '../components/ProgressMeter.vue'
const loading = ref(true)
const items = ref<Question[]>([]), index = ref(0), answer = ref(''), confidence = ref(3), result = ref<{ outcome: string; nextReviewAt: string } | null>(null), error = ref(''), busy = ref(false), correct = ref(0), incorrect = ref(0), skipped = ref(0)
const current = computed(() => items.value[index.value]); let started = Date.now(), requestId = crypto.randomUUID()
onMounted(async () => { try { items.value = (await api.get<Question[]>('/reviews/today')).data; started = Date.now() } catch (e) { error.value = errorText(e) } finally { loading.value = false } })
async function submit(status: string) { if (!current.value) return; busy.value = true; error.value = ''; try { result.value = (await api.post(`/reviews/${current.value.id}/complete`, { requestId, result: status, answer: answer.value, confidence: confidence.value, timeSpent: Math.min(86400, Math.floor((Date.now() - started) / 1000)) })).data; if (result.value?.outcome === 'CORRECT') correct.value++; else if (result.value?.outcome === 'SKIP') skipped.value++; else incorrect.value++ } catch (e) { error.value = errorText(e) } finally { busy.value = false } }
function next() { index.value++; result.value = null; answer.value = ''; confidence.value = 3; started = Date.now(); requestId = crypto.randomUUID() }
</script>
<template><PageHeader title="每日复习"><template #description><p class="muted">{{ items.length ? `进度 ${Math.min(index + 1, items.length)} / ${items.length}` : '今日复习安排' }}</p></template></PageHeader><p v-if="error" class="error" role="alert">{{ error }}</p><section v-if="items.length" class="panel review-progress"><ProgressMeter :value="correct + incorrect + skipped" :total="items.length" label="本次复习进度" :detail="(correct + incorrect + skipped) + ' / ' + items.length + ' 道已处理'" /><div class="review-totals"><span><AppIcon name="check" :size="16" />正确 {{ correct }}</span><span><AppIcon name="book" :size="16" />需巩固 {{ incorrect }}</span><span><AppIcon name="clock" :size="16" />跳过 {{ skipped }}</span></div></section><section v-if="current" class="panel review-panel"><span class="tag">{{ current.questionType }}</span><p class="reading">{{ current.content }}</p><label v-for="(option,key) in current.options" :key="key" class="option selectable" :class="{ selected: answer === key }"><input v-model="answer" type="radio" :value="key" :disabled="!!result"><strong>{{ key }}</strong><span>{{ option }}</span></label><label v-if="current.questionType === '申论'">我的练习<textarea v-model="answer" rows="6" :disabled="!!result" maxlength="5000"></textarea></label><label>把握程度<select v-model.number="confidence" :disabled="!!result"><option :value="1">1 · 很不确定</option><option :value="2">2 · 需要提示</option><option :value="3">3 · 基本理解</option><option :value="4">4 · 可以独立完成</option><option :value="5">5 · 熟练掌握</option></select></label><div v-if="!result" class="actions"><button class="button" :disabled="busy || !answer" @click="submit('CORRECT')">{{ current.questionType === '申论' ? '自评：基本掌握' : '提交答案' }}</button><button v-if="current.questionType === '申论'" class="button secondary" :disabled="busy" @click="submit('INCORRECT')">自评：仍需巩固</button><button class="text-button" :disabled="busy" @click="submit('SKIP')">暂时跳过</button></div><div v-else class="review-result"><h3>{{ result.outcome === 'CORRECT' ? '回答正确' : result.outcome === 'SKIP' ? '已安排再次复习' : '需要再巩固一次' }}</h3><p>参考答案：{{ current.correctAnswer }}</p><MarkdownContent class="reading" :content="current.explanation || current.analysis?.correctAnswerExplanation || '这道题尚未填写解析。'" /><p class="muted">下次复习：{{ formatTime(result.nextReviewAt) }}</p><button class="button" @click="next">{{ index + 1 === items.length ? '完成复习' : '下一题' }}</button></div></section><p v-else-if="loading" class="loading-state" role="status">正在读取复习安排…</p><section v-else-if="!error" class="panel empty review-empty"><h2>{{ items.length ? '本次复习已完成' : '今天没有到期错题' }}</h2><p>正确 {{ correct }} · 需巩固 {{ incorrect }} · 跳过 {{ skipped }}</p><p class="muted">每次复习都会更新下一次复习日期。</p><RouterLink class="button" to="/">返回今日学习</RouterLink></section></template>
